name: CI

on:
  push:
    branches: [ main, master, add-db ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "cr.selcloud.ru/algol"
  IMAGE_NAME: "chat-server"
  CONTAINER_NAME: "chat-server-container"
  DB_CONTAINER_NAME: "pgchat-prod"
  DB_IMAGE_NAME: "postgres:14-alpine3.17"

jobs:
  linter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.61

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          args: --timeout=30m --config=./.golangci.pipeline.yaml

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

  build-and-test:
    runs-on: ubuntu-latest
    needs: linter
    steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23'
            cache-dependency-path: go.sum

        - name: Build
          run: go build -o ./bin/ -v ./...

        - name: Test
          run: go test -v ./...

  image-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Встаем на нужную ветку в гитхабе
      - name: Checkout master
      #- name: Checkout add-db
        uses: actions/checkout@v3

      - name: Create .env file for CI
        run: |
          echo "PG_DATABASE_NAME=chat" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_PORT=54332" >> .env
          echo "MIGRATION_DIR=./migrations" >> .env
          echo "GRPC_HOST=0.0.0.0" >> .env
          echo "GRPC_PORT=50062" >> .env
          echo "PG_DSN=host=$DB_CONTAINER_NAME port=5432 dbname=chat user=${{secrets.PG_USER}} password=${{secrets.PG_PASSWORD}} sslmode=disable" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile .

      - name: Build and Push Migrator Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build --no-cache --push --tag $REGISTRY/chat-migrator:$TAG_NAME -f migration_prod.Dockerfile .

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,CONTAINER_NAME,DB_CONTAINER_NAME,DB_IMAGE_NAME
          script: |
            # Создаем файл .env
            echo "PG_DATABASE_NAME=chat" >> .env
            echo "PG_USER=${{ secrets.PG_USER }}" >> .env
            echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
            echo "PG_PORT=54332" >> .env
            echo "MIGRATION_DIR=./migrations" >> .env
            echo "GRPC_HOST=45.130.9.109" >> .env
            echo "GRPC_PORT=50062" >> .env

            # Set up variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)  

            # Создаем сеть
            docker network create chat-service-network || true

            # Login into Selectel Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY
            
            # Stop running container
            docker stop $CONTAINER_NAME
            
            # Remove old container
            docker rm $CONTAINER_NAME

            # Run a new container from a new image
            docker run -d -p 50062:50062 --network chat-service-network --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME

            # Stop running old DB container
            docker rm $DB_CONTAINER_NAME --force
            
            # Run a new DB container
            docker run -d --name $DB_CONTAINER_NAME \
            --network chat-service-network \
            -e POSTGRES_DB=chat \
            -e POSTGRES_USER=${{ secrets.PG_USER }}  \
            -e POSTGRES_PASSWORD=${{ secrets.PG_PASSWORD }} \
            -v postgres_data:/var/lib/postgresql/data \
            -p 54331:5432 $DB_IMAGE_NAME

            # Stop old migrator container
            docker rm chat-migrator --force
            
            # Launch new migrator container
            docker run --network chat-service-network --name chat-migrator \
            --env-file .env \
            -e DB_HOST=$DB_CONTAINER_NAME -t $REGISTRY/chat-migrator:$TAG_NAME
